### ISSUE TITLE
Version Question

### ISSUE THREAD

**Issue by KillTheBoy2023** [IPADS-DuVisor/rocket-chip#1]
The rocket-chip you are using is very outdated(Dec 19, 2020). Do you have any considerations and why you are using this version,  does this approach bring any convenience?  Looking forward to your reply.

**Comment by 130B848** [comment]
We used this version just because this project was started from 2020, we chosed a FireSim-compatible version and kept using it.

The FireSim platform did not frequently update its RocketChip as well as its Linux kernel. Besides, different FireSim versions are likely to have compatiblity issues with RocketChip and Linux kernel. (Maybe these issues are because the code and interfaces exposed by RocketChip are not stable.)

**Comment by KillTheBoy2023** [comment]
Thanks
